# Generated by Django 5.2.1 on 2025-06-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кухни')),
                ('facade_type', models.CharField(max_length=200, verbose_name='Вид фасада')),
                ('facade_image', models.ImageField(upload_to='facade_images/', verbose_name='Изображение фасада')),
                ('facade_coating', models.CharField(max_length=200, verbose_name='Покрытие фасадов')),
                ('size', models.CharField(max_length=100, verbose_name='Размер кухни')),
                ('island_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры кухонного острова')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kitchen_images/', verbose_name='Изображение кухни')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.kitchen')),
            ],
        ),
    ]
