# Generated by Django 5.2.1 on 2025-06-22 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название гардеробной')),
                ('main_image', models.ImageField(upload_to='garders/main/', verbose_name='Главное изображение')),
                ('size', models.CharField(max_length=100, verbose_name='Размер шкафа на фото')),
                ('corpus', models.CharField(max_length=200, verbose_name='Корпус')),
                ('mdf_thickness', models.CharField(max_length=100, verbose_name='Толщина МДФ')),
                ('drilling', models.CharField(max_length=200, verbose_name='Присадка')),
            ],
        ),
        migrations.CreateModel(
            name='GarderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garders/additional/', verbose_name='Дополнительное изображение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('garder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.garder')),
            ],
        ),
    ]
