# Generated by Django 5.2.1 on 2025-06-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_garderimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='facades/')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=255, verbose_name='Вид фасада')),
                ('frame', models.CharField(max_length=255, verbose_name='Рамка')),
                ('panel', models.CharField(max_length=255, verbose_name='Филёнка')),
            ],
        ),
        migrations.CreateModel(
            name='FinishingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('facade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main.facade')),
            ],
        ),
        migrations.CreateModel(
            name='FinishingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='facades/colors/')),
                ('code', models.CharField(blank=True, help_text='Код цвета или артикул', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main.finishingmaterial')),
            ],
        ),
    ]
