# Generated by Django 5.2.1 on 2025-06-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_facade_finishingmaterial_finishingcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facade',
            name='name',
        ),
    ]
