# Generated by Django 5.2.1 on 2025-08-25 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_facade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ванной')),
                ('main_image', models.ImageField(upload_to='bath/main/', verbose_name='Главное изображение')),
                ('size', models.CharField(max_length=100, verbose_name='Размер шкафа на фото')),
                ('corpus', models.CharField(max_length=200, verbose_name='Корпус')),
                ('mdf_thickness', models.CharField(max_length=100, verbose_name='Толщина МДФ')),
                ('drilling', models.CharField(max_length=200, verbose_name='Присадка')),
            ],
        ),
        migrations.CreateModel(
            name='BathImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bath/additional/', verbose_name='Дополнительное изображение')),
                ('bath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.bath', verbose_name='Ванная')),
            ],
        ),
    ]
