# Generated by Django 5.2.1 on 2025-08-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bath_bathimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathimage',
            name='bath',
        ),
        migrations.DeleteModel(
            name='Bath',
        ),
        migrations.DeleteModel(
            name='BathImage',
        ),
    ]
