--
-- PostgreSQL database dump
--

\restrict I6BX7R0zfUZb9LtVu63A3Lp0sdsuC9YccKHdhatlMIQaiPdDy4gm7w6FdijQMuC

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: main_facade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_facade (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    main_image character varying(100) NOT NULL,
    type character varying(255) NOT NULL,
    frame character varying(255) NOT NULL,
    panel character varying(255) NOT NULL
);


ALTER TABLE public.main_facade OWNER TO postgres;

--
-- Name: main_facade_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_facade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_facade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_finishingcolor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_finishingcolor (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    image character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    material_id bigint NOT NULL
);


ALTER TABLE public.main_finishingcolor OWNER TO postgres;

--
-- Name: main_finishingcolor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_finishingcolor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_finishingcolor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_finishingmaterial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_finishingmaterial (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    facade_id bigint NOT NULL
);


ALTER TABLE public.main_finishingmaterial OWNER TO postgres;

--
-- Name: main_finishingmaterial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_finishingmaterial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_finishingmaterial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_garder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_garder (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    main_image character varying(100) NOT NULL,
    size character varying(100) NOT NULL,
    corpus character varying(200) NOT NULL,
    mdf_thickness character varying(100) NOT NULL,
    drilling character varying(200) NOT NULL
);


ALTER TABLE public.main_garder OWNER TO postgres;

--
-- Name: main_garder_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_garder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_garder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_garderimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_garderimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    garder_id bigint NOT NULL
);


ALTER TABLE public.main_garderimage OWNER TO postgres;

--
-- Name: main_garderimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_garderimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_garderimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_kitchen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_kitchen (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    facade_type character varying(200) NOT NULL,
    facade_image character varying(100) NOT NULL,
    facade_coating character varying(200) NOT NULL,
    size character varying(100) NOT NULL,
    island_size character varying(100)
);


ALTER TABLE public.main_kitchen OWNER TO postgres;

--
-- Name: main_kitchen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_kitchen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_kitchen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_kitchenimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_kitchenimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    kitchen_id bigint NOT NULL
);


ALTER TABLE public.main_kitchenimage OWNER TO postgres;

--
-- Name: main_kitchenimage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_kitchenimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_kitchenimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: main_facade; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_facade (id, title, main_image, type, frame, panel) FROM stdin;
18	18	https://storage.yandexcloud.net/mark2/facades/facade- (18).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
17	17	https://storage.yandexcloud.net/mark2/facades/facade- (17).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
16	16	https://storage.yandexcloud.net/mark2/facades/facade- (16).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
15	15	https://storage.yandexcloud.net/mark2/facades/facade- (15).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
14	14	https://storage.yandexcloud.net/mark2/facades/facade- (14).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
13	13	https://storage.yandexcloud.net/mark2/facades/facade- (13).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
11	11	https://storage.yandexcloud.net/mark2/facades/facade- (11).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
9	9	https://storage.yandexcloud.net/mark2/facades/facade- (9).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
8	8	https://storage.yandexcloud.net/mark2/facades/facade- (8).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
7	7	https://storage.yandexcloud.net/mark2/facades/facade- (7).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
6	6	https://storage.yandexcloud.net/mark2/facades/facade- (6).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
5	5	https://storage.yandexcloud.net/mark2/facades/facade- (5).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
4	4	https://storage.yandexcloud.net/mark2/facades/facade- (4).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
2	2	https://storage.yandexcloud.net/mark2/facades/facade- (2).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
1	1	https://storage.yandexcloud.net/mark2/facades/facade- (1).jpg	фасад из массива, соединение шип-паз	массив (100x20 мм)	MDF / шпон
3	3	https://storage.yandexcloud.net/mark2/facades/facade- (3).jpg	МДФ	массив (100x20 мм)	MDF / шпон
10	10	https://storage.yandexcloud.net/mark2/facades/facade- (10).jpg	Шпон	массив (100x20 мм)	MDF / шпон
12	12	https://storage.yandexcloud.net/mark2/facades/facade- (12).jpg	Массив из дерева	массив (100x20 мм)	MDF / шпон
\.


--
-- Data for Name: main_finishingcolor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_finishingcolor (id, name, image, code, material_id) FROM stdin;
\.


--
-- Data for Name: main_finishingmaterial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_finishingmaterial (id, name, description, facade_id) FROM stdin;
\.


--
-- Data for Name: main_garder; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_garder (id, title, main_image, size, corpus, mdf_thickness, drilling) FROM stdin;
1	370	https://storage.yandexcloud.net/mark2/garders/garder370.jpg	2600/2550/600 мм	на выбор более 180 цветов ДСП, МДФ, Шпон, Глянец, Кожа.	10,16,19, 22, 25 мм	Присадка под петли на МДФ от 16 мм
\.


--
-- Data for Name: main_garderimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_garderimage (id, image, garder_id) FROM stdin;
1	https://storage.yandexcloud.net/mark2/kitchens/Kitchen086.jpg	1
\.


--
-- Data for Name: main_kitchen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_kitchen (id, name, facade_type, facade_image, facade_coating, size, island_size) FROM stdin;
1	1	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_1.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
2	2	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_2.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
3	3	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_3.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
4	4	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_4.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
5	5	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_5.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
6	6	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_6.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
7	7	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_7.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
8	8	Ламинированные фасады, На основе MDF	https://storage.yandexcloud.net/mark2/kitchens/kitchen_8.jpg	Матовый фасад, Прямые фасады, Система без ручек	360 cm x 300 cm	280 cm
\.


--
-- Data for Name: main_kitchenimage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_kitchenimage (id, image, kitchen_id) FROM stdin;
1	https://storage.yandexcloud.net/mark2/kitchens/kitchen_1(2).jpg	1
3	https://storage.yandexcloud.net/mark2/kitchens/kitchen_2(2).jpg	2
4	https://storage.yandexcloud.net/mark2/kitchens/kitchen_2(3).jpg	2
5	https://storage.yandexcloud.net/mark2/kitchens/kitchen_3(2).jpg	3
7	https://storage.yandexcloud.net/mark2/kitchens/kitchen_4(2).jpg	4
9	https://storage.yandexcloud.net/mark2/kitchens/kitchen_5(2).jpg	5
10	https://storage.yandexcloud.net/mark2/kitchens/kitchen_5(3).jpg	5
\.


--
-- Name: main_facade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_facade_id_seq', 1, false);


--
-- Name: main_finishingcolor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_finishingcolor_id_seq', 1, false);


--
-- Name: main_finishingmaterial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_finishingmaterial_id_seq', 1, false);


--
-- Name: main_garder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_garder_id_seq', 1, false);


--
-- Name: main_garderimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_garderimage_id_seq', 1, false);


--
-- Name: main_kitchen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_kitchen_id_seq', 1, false);


--
-- Name: main_kitchenimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_kitchenimage_id_seq', 1, false);


--
-- Name: main_facade main_facade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_facade
    ADD CONSTRAINT main_facade_pkey PRIMARY KEY (id);


--
-- Name: main_finishingcolor main_finishingcolor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_finishingcolor
    ADD CONSTRAINT main_finishingcolor_pkey PRIMARY KEY (id);


--
-- Name: main_finishingmaterial main_finishingmaterial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_finishingmaterial
    ADD CONSTRAINT main_finishingmaterial_pkey PRIMARY KEY (id);


--
-- Name: main_garder main_garder_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_garder
    ADD CONSTRAINT main_garder_pkey PRIMARY KEY (id);


--
-- Name: main_garderimage main_garderimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_garderimage
    ADD CONSTRAINT main_garderimage_pkey PRIMARY KEY (id);


--
-- Name: main_kitchen main_kitchen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_kitchen
    ADD CONSTRAINT main_kitchen_pkey PRIMARY KEY (id);


--
-- Name: main_kitchenimage main_kitchenimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_kitchenimage
    ADD CONSTRAINT main_kitchenimage_pkey PRIMARY KEY (id);


--
-- Name: main_finishingcolor_material_id_1495ac06; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_finishingcolor_material_id_1495ac06 ON public.main_finishingcolor USING btree (material_id);


--
-- Name: main_finishingmaterial_facade_id_f3bd84f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_finishingmaterial_facade_id_f3bd84f2 ON public.main_finishingmaterial USING btree (facade_id);


--
-- Name: main_garderimage_garder_id_99b36735; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_garderimage_garder_id_99b36735 ON public.main_garderimage USING btree (garder_id);


--
-- Name: main_kitchenimage_kitchen_id_bbfffd18; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX main_kitchenimage_kitchen_id_bbfffd18 ON public.main_kitchenimage USING btree (kitchen_id);


--
-- Name: main_finishingcolor main_finishingcolor_material_id_1495ac06_fk_main_fini; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_finishingcolor
    ADD CONSTRAINT main_finishingcolor_material_id_1495ac06_fk_main_fini FOREIGN KEY (material_id) REFERENCES public.main_finishingmaterial(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_finishingmaterial main_finishingmaterial_facade_id_f3bd84f2_fk_main_facade_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_finishingmaterial
    ADD CONSTRAINT main_finishingmaterial_facade_id_f3bd84f2_fk_main_facade_id FOREIGN KEY (facade_id) REFERENCES public.main_facade(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_garderimage main_garderimage_garder_id_99b36735_fk_main_garder_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_garderimage
    ADD CONSTRAINT main_garderimage_garder_id_99b36735_fk_main_garder_id FOREIGN KEY (garder_id) REFERENCES public.main_garder(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_kitchenimage main_kitchenimage_kitchen_id_bbfffd18_fk_main_kitchen_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_kitchenimage
    ADD CONSTRAINT main_kitchenimage_kitchen_id_bbfffd18_fk_main_kitchen_id FOREIGN KEY (kitchen_id) REFERENCES public.main_kitchen(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict I6BX7R0zfUZb9LtVu63A3Lp0sdsuC9YccKHdhatlMIQaiPdDy4gm7w6FdijQMuC

